name: Pre-merge

on:
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

env:
  ORG_GRADLE_PROJECT_githubPackagesUsername: kyhule
  ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          pwd
          ls -al

      - name: Checkout the theme repo
        uses: actions/checkout@v3
        with:
          path: polyworld-theme

      - run: |
          pwd
          ls -al

      - name: Checkout the app repo
        uses: actions/checkout@v3
        with:
          repository: kyhule/polyworld-app
          path: polyworld-app

      - run: |
          pwd
          ls -al

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Android
        uses: android-actions/setup-android@v2

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Set up composite include
        working-directory: polyworld-theme
        run: |
          touch .composite-include

      - name: Build and Test theme
        working-directory: polyworld-theme
        run: >
          ./gradlew
          build
          --info

      - name: Assemble debug app
        working-directory: polyworld-app
        run: >
          ./gradlew
          assembleDebug
          --info
#
#      - name: Check test output existence
#        id: check_test_output
#        uses: andstor/file-existence-action@v2
#        if: success() || failure()
#        with:
#          files: '**/build/test-results/**/*.xml'
#
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: steps.check_test_outputs.file_exists == 'true'
#        with:
#          name: Junit Tests
#          path: '**/build/test-results/**/*.xml'
#          reporter: java-junit
#          fail-on-error: false
